"""Shared animation mappings, priorities, layers and defaults for Player.

Layer priority system (lower number = higher priority / overrides higher numbers):
  -1: cinematic    — scripted/cutscene sequences
   0: death        — always wins, cannot be cancelled
   1: physics      — hard falls, knockdowns, ground impacts
   2: stability    — staggers, slides, guard breaks
   3: action       — attacks, dashes, casts, blocks, parkour
   4: locomotion   — run, walk, jump, swim, fly, crouch
   5: modifier     — surface modifiers, context overlays
"""

# ---------------------------------------------------------------------------
# Layer priority table (lower = wins)
# ---------------------------------------------------------------------------
LAYER_PRIORITY = {
    "cinematic":  -1,
    "death":       0,
    "physics":     1,
    "stability":   2,
    "action":      3,
    "locomotion":  4,
    "modifier":    5,
}

# ---------------------------------------------------------------------------
# State → layer mapping
# ---------------------------------------------------------------------------
STATE_LAYER_MAP: dict[str, str] = {
    # Death / Cinematic
    "dead":                 "death",
    "death":                "death",
    "cinematic":            "cinematic",

    # Physics (Priority 1 - hard uninterruptible events)
    "falling_hard":         "physics",
    "knocked_down":         "physics",
    "ground_impact":        "physics",
    "land_hard":            "physics",
    "land_collapse":        "physics",
    "wall_impact_high":     "physics",
    "uncontrolled":         "physics",
    "collapse":             "physics",

    # Stability (Priority 2)
    "stagger":              "stability",
    "staggered":            "stability",
    "knockback":            "stability",
    "guard_break":          "stability",
    "sliding":              "stability",
    "slide_forward":        "stability",
    "slide_side":           "stability",
    "slide_back":           "stability",
    "recovering":           "stability",
    "major_unstable":       "stability",

    # Action (Priority 3)
    "attacking":            "action",
    "attack_light":         "action",
    "attack_heavy":         "action",
    "attack_dual":          "action",
    "attack_air":           "action",
    "attack_dash":          "action",
    "attack_finisher":      "action",
    "blocking":             "action",
    "block_raise":          "action",
    "block_hold":           "action",
    "block_perfect":        "action",
    "dodging":              "action",
    "dash_forward":         "action",
    "dash_back":            "action",
    "dash_left":            "action",
    "dash_right":           "action",
    "casting":              "action",
    "cast_prepare":         "action",
    "cast_channel":         "action",
    "cast_release":         "action",
    "cast_interrupt":       "action",
    "cast_overstrain":      "action",
    "vaulting":             "action",
    "vault_low":            "action",
    "vault_high":           "action",
    "vault_speed":          "action",
    "climbing":             "action",
    "climb_fast":           "action",
    "climb_slow":           "action",
    "wallrun":              "action",
    "wallrun_start":        "action",
    "wallrun_exit":         "action",
    "wall_jump":            "action",
    "grab_ledge":           "action",
    "interaction_use":      "action",
    "interaction_push":     "action",
    "interaction_pull":     "action",
    "interaction_lift":     "action",
    "interaction_break":    "action",

    # Damage response
    "light_hit":            "stability",
    "heavy_hit":            "stability",
    "air_hit":              "stability",
    "wall_impact":          "stability",
    "limb_impact":          "stability",

    # Locomotion (Priority 4)
    "idle":                 "locomotion",
    "idle_relaxed":         "locomotion",
    "idle_combat":          "locomotion",
    "idle_injured":         "locomotion",
    "walking":              "locomotion",
    "walk":                 "locomotion",
    "walk_uphill":          "locomotion",
    "walk_downhill":        "locomotion",
    "running":              "locomotion",
    "run":                  "locomotion",
    "sprinting":            "locomotion",
    "sprint":               "locomotion",
    "sprint_stop":          "locomotion",
    "crouch_idle":          "locomotion",
    "crouch_move":          "locomotion",
    "turn_in_place":        "locomotion",
    "jumping":              "locomotion",
    "jump":                 "locomotion",
    "jump_start":           "locomotion",
    "jump_dash":            "locomotion",
    "in_air":               "locomotion",
    "falling":              "locomotion",
    "land_soft":            "locomotion",
    "land_roll":            "locomotion",
    "landing":              "locomotion",
    "swim":                 "locomotion",
    "swim_surface":         "locomotion",
    "swim_dive":            "locomotion",
    "swim_underwater":      "locomotion",
    "swim_panic":           "locomotion",
    "swim_exit":            "locomotion",
    "flying":               "locomotion",
    "fly":                  "locomotion",
    "flight_takeoff":       "locomotion",
    "flight_glide":         "locomotion",
    "flight_hover":         "locomotion",
    "flight_dive":          "locomotion",
    "flight_airdash":       "locomotion",
    "flight_land":          "locomotion",
    "mounted_idle":         "locomotion",
    "mounted_move":         "locomotion",
    "mounted_ship_idle":    "locomotion",
    "mounted_ship_move":    "locomotion",
    "mounting":             "locomotion",
    "dismounting":          "locomotion",

    # Modifier (Priority 5 — overlays, not blocking)
    "terrain_uphill":       "modifier",
    "terrain_downhill":     "modifier",
    "terrain_mud":          "modifier",
    "terrain_slippery":     "modifier",
    "terrain_soft":         "modifier",
    "minor_unstable":       "modifier",
}

# ---------------------------------------------------------------------------
# States that cannot be interrupted by anything (priority check exemption)
# ---------------------------------------------------------------------------
UNINTERRUPTIBLE_STATES: frozenset[str] = frozenset({
    "dead",
    "death",
    "falling_hard",
    "knocked_down",
    "ground_impact",
    "collapse",
    "land_collapse",
    "wall_impact_high",
    "cinematic",
})

# ---------------------------------------------------------------------------
# Known context flag names (populated each frame on player)
# ---------------------------------------------------------------------------
CONTEXT_FLAG_NAMES: tuple[str, ...] = (
    "wall_contact",
    "edge_detected",
    "slippery_surface",
    "soft_surface",
    "steep_slope",
    "uneven_ground",
    "in_mud",
    "in_water",
    "in_air_current",
    "low_ceiling",
    "obstacle_ahead",
    "destructible_surface",
)

# ---------------------------------------------------------------------------
# Per-state interruption rules: which LAYERS can interrupt this state
# (empty list = only lower-priority layers can interrupt, per normal rules)
# ---------------------------------------------------------------------------
INTERRUPT_RULES: dict[str, list[str]] = {
    "cast_channel":   ["physics", "stability"],
    "cast_prepare":   ["physics", "stability"],
    "casting":        ["physics", "stability"],
    "attack_light":   ["physics", "stability"],
    "attack_heavy":   ["physics", "stability"],
    "attack_finisher":["physics"],              # finisher can't be broken by staggers
    "blocking":       ["physics", "stability"],
    "block_perfect":  ["physics"],
    "dash_forward":   ["physics", "stability"],
    "dash_back":      ["physics", "stability"],
    "wallrun":        ["physics", "stability"],
    "climbing":       ["physics", "stability"],
    "vault_low":      ["physics", "stability"],
    "vault_high":     ["physics", "stability"],
}

# ---------------------------------------------------------------------------
# Fallback animation chains (state → ordered list of clip names to try)
# ---------------------------------------------------------------------------
STATE_ANIM_FALLBACK = {
    "idle":             ["idle"],
    "idle_relaxed":     ["idle_relaxed", "idle"],
    "idle_combat":      ["idle_combat", "idle"],
    "idle_injured":     ["idle_injured", "idle"],
    "walking":          ["walk", "idle"],
    "walk":             ["walk", "idle"],
    "walk_uphill":      ["walk_uphill", "walk", "idle"],
    "walk_downhill":    ["walk_downhill", "walk", "idle"],
    "running":          ["run", "walk"],
    "run":              ["run", "walk"],
    "sprinting":        ["sprint", "run", "walk"],
    "sprint":           ["sprint", "run", "walk"],
    "sprint_stop":      ["sprint_stop", "run", "idle"],
    "crouch_idle":      ["crouch_idle", "idle"],
    "crouch_move":      ["crouch_move", "walk", "idle"],
    "turn_in_place":    ["turn_in_place", "idle"],
    "jumping":          ["run", "walk", "idle"],
    "jump":             ["run", "walk", "idle"],
    "jump_start":       ["jump_start", "run", "walk"],
    "jump_dash":        ["jump_start", "run"],
    "falling":          ["run", "walk", "idle"],
    "in_air":           ["run", "walk", "idle"],
    "landing":          ["idle", "walk"],
    "land_soft":        ["landing", "idle"],
    "land_hard":        ["land_hard", "landing", "idle"],
    "land_roll":        ["land_roll", "landing", "idle"],
    "land_collapse":    ["land_collapse", "stagger", "landing"],
    "attacking":        ["run", "walk"],
    "attack_light":     ["attack_light", "run", "walk"],
    "attack_heavy":     ["attack_heavy", "run", "walk"],
    "attack_dual":      ["attack_dual", "attack_light", "run"],
    "attack_air":       ["attack_air", "run", "walk"],
    "attack_dash":      ["attack_dash", "dodging", "run"],
    "attack_finisher":  ["attack_finisher", "attack_heavy"],
    "dodging":          ["run", "walk"],
    "dash_forward":     ["dash_forward", "dodging", "run"],
    "dash_back":        ["dash_back", "dodging", "run"],
    "dash_left":        ["dash_left", "dodging", "run"],
    "dash_right":       ["dash_right", "dodging", "run"],
    "blocking":         ["idle", "walk"],
    "block_raise":      ["block_raise", "blocking", "idle"],
    "block_hold":       ["block_hold", "blocking", "idle"],
    "block_perfect":    ["block_perfect", "blocking", "idle"],
    "casting":          ["idle", "run"],
    "cast_prepare":     ["cast_prepare", "casting", "idle"],
    "cast_channel":     ["cast_channel", "casting", "idle"],
    "cast_release":     ["cast_release", "casting", "idle"],
    "cast_interrupt":   ["cast_interrupt", "stagger", "idle"],
    "cast_overstrain":  ["cast_overstrain", "stagger", "idle"],
    "vaulting":         ["run", "walk"],
    "vault_low":        ["vault_low", "vaulting", "run"],
    "vault_high":       ["vault_high", "vaulting", "run"],
    "vault_speed":      ["vault_speed", "vaulting", "run"],
    "climbing":         ["run", "walk"],
    "climb_fast":       ["climb_fast", "climbing", "run"],
    "climb_slow":       ["climb_slow", "climbing", "run"],
    "wallrun":          ["run", "walk"],
    "wallrun_start":    ["wallrun_start", "wallrun", "run"],
    "wallrun_exit":     ["wallrun_exit", "run", "jumping"],
    "wall_jump":        ["wall_jump", "jumping", "run"],
    "grab_ledge":       ["grab_ledge", "climbing", "run"],
    "stagger":          ["stagger", "staggered", "landing", "idle"],
    "staggered":        ["staggered", "landing", "idle"],
    "knockback":        ["knockback", "stagger", "landing"],
    "guard_break":      ["guard_break", "stagger", "idle"],
    "sliding":          ["sliding", "dodging", "run", "walk"],
    "recovering":       ["recovering", "landing", "idle"],
    "falling_hard":     ["falling_hard", "falling", "jumping", "run"],
    "knocked_down":     ["knocked_down", "stagger", "landing"],
    "light_hit":        ["light_hit", "stagger", "idle"],
    "heavy_hit":        ["heavy_hit", "stagger", "landing"],
    "air_hit":          ["air_hit", "falling", "jumping"],
    "mounting":         ["mounting", "climbing", "vaulting", "idle"],
    "mounted_idle":     ["mounted_idle", "idle", "walk"],
    "mounted_move":     ["mounted_move", "walk", "run"],
    "mounted_ship_idle":["mounted_ship_idle", "mounted_idle", "idle"],
    "mounted_ship_move":["mounted_ship_move", "mounted_move", "walk"],
    "dismounting":      ["dismounting", "landing", "idle"],
    "swim":             ["swim", "walk", "idle"],
    "swim_surface":     ["swim_surface", "swim", "walk"],
    "swim_dive":        ["swim_dive", "swim"],
    "swim_underwater":  ["swim_underwater", "swim", "walk"],
    "swim_panic":       ["swim_panic", "swim", "run"],
    "swim_exit":        ["swim_exit", "swim", "landing"],
    "flying":           ["flying", "jump", "run", "idle"],
    "fly":              ["flying", "jump", "run", "idle"],
    "flight_takeoff":   ["flight_takeoff", "flying", "jump"],
    "flight_glide":     ["flight_glide", "flying", "run"],
    "flight_hover":     ["flight_hover", "flying", "idle"],
    "flight_dive":      ["flight_dive", "flying", "falling"],
    "flight_airdash":   ["flight_airdash", "flying", "run"],
    "dead":             ["dead", "idle"],
    "walk":             ["walk", "idle"],
    "run":              ["run", "walk"],
    "jump":             ["run", "walk"],
    "interaction_use":  ["interaction_use", "idle"],
    "interaction_push": ["interaction_push", "idle"],
    "interaction_pull": ["interaction_pull", "idle"],
    "interaction_lift": ["interaction_lift", "idle"],
    "interaction_break":["interaction_break", "attack_heavy", "idle"],
}


ANIM_TOKEN_ALIASES = {
    "idleloop":         ["idle"],
    "idle_relaxed":     ["idle_relaxed", "idle"],
    "walkloop":         ["walk"],
    "sprintloop":       ["run", "walk"],
    "jumpstart":        ["run", "walk"],
    "fallloop":         ["run", "walk"],
    "jumpland":         ["idle", "walk"],
    "swordslash":       ["attack_light", "run", "walk"],
    "attack_light":     ["attack_light", "run", "walk"],
    "attack_heavy":     ["attack_heavy", "run"],
    "dodgebackward":    ["dash_back", "dodging", "run", "walk"],
    "blockidle":        ["block_hold", "idle", "walk"],
    "spellcast":        ["cast_release", "casting", "idle", "run"],
    "spellprepare":     ["cast_prepare", "casting", "idle"],
    "spellchannel":     ["cast_channel", "casting", "idle"],
    "vaultover":        ["vault_low", "vaulting", "run", "walk"],
    "ledgeclimb":       ["climb_fast", "climbing", "run", "walk"],
    "wallrun":          ["wallrun", "run", "walk"],
    "sliding":          ["sliding", "dodging", "run", "walk"],
    "staggered":        ["stagger", "staggered", "landing", "idle"],
    "fallinghard":      ["falling_hard", "falling", "jumping", "run"],
    "recovering":       ["recovering", "landing", "idle"],
    "mountstart":       ["mounting", "climbing", "vaulting", "idle"],
    "mounting":         ["mounting", "climbing", "vaulting", "idle"],
    "mountedidle":      ["mounted_idle", "idle", "walk"],
    "mountedmove":      ["mounted_move", "walk", "run"],
    "mountedshipidle":  ["mounted_ship_idle", "mounted_idle", "idle"],
    "mountedshipmove":  ["mounted_ship_move", "mounted_move", "walk"],
    "dismount":         ["dismounting", "landing", "idle"],
    "dismounting":      ["dismounting", "landing", "idle"],
    "death":            ["dead", "idle"],
    "swim":             ["swim", "walk", "idle"],
    "flying":           ["flying", "jump", "run", "idle"],
    "fly":              ["flying", "jump", "run", "idle"],
    "hover":            ["flight_hover", "flying", "idle"],
    "flight":           ["flying", "jump", "run", "idle"],
    "jump":             ["run", "walk"],
    "dash":             ["dash_forward", "dodging", "run"],
}


DEFAULT_STATE_DURATIONS = {
    # Locomotion transitions
    "landing":          0.30,
    "land_hard":        0.60,
    "land_roll":        0.90,
    "land_collapse":    1.20,
    "jump_start":       0.25,
    "sprint_stop":      0.35,
    "turn_in_place":    0.25,
    # Action
    "attacking":        0.40,
    "attack_light":     0.42,
    "attack_heavy":     0.65,
    "attack_dual":      0.55,
    "attack_air":       0.50,
    "attack_dash":      0.38,
    "attack_finisher":  1.20,
    "dodging":          0.45,
    "dash_forward":     0.38,
    "dash_back":        0.38,
    "dash_left":        0.35,
    "dash_right":       0.35,
    "casting":          0.55,
    "cast_prepare":     0.30,
    "cast_channel":     0.0,   # looping until released
    "cast_release":     0.25,
    "cast_interrupt":   0.35,
    "cast_overstrain":  0.65,
    "vaulting":         0.55,
    "vault_low":        0.45,
    "vault_high":       0.65,
    "vault_speed":      0.40,
    "climbing":         0.70,
    "climb_fast":       0.60,
    "climb_slow":       0.80,
    "wallrun":          0.60,
    "wallrun_start":    0.30,
    "wallrun_exit":     0.25,
    "wall_jump":        0.30,
    "grab_ledge":       0.55,
    "block_raise":      0.20,
    "block_perfect":    0.40,
    "guard_break":      0.75,
    "interaction_use":  0.60,
    "interaction_push": 0.70,
    "interaction_pull": 0.70,
    "interaction_lift": 0.80,
    "interaction_break":1.00,
    # Stability/Physics
    "stagger":          0.45,
    "staggered":        0.45,
    "knockback":        0.55,
    "light_hit":        0.20,
    "heavy_hit":        0.50,
    "air_hit":          0.40,
    "guard_break":      0.75,
    "sliding":          0.35,
    "recovering":       0.35,
    "falling_hard":     0.75,
    "knocked_down":     1.10,
    "collapse":         1.30,
    # Mountings
    "mounting":         0.55,
    "dismounting":      0.45,
    # Death
    "dead":             1.20,
    "death":            1.20,
    # Swim
    "swim_exit":        0.40,
    # Flight
    "flight_takeoff":   0.50,
    "flight_airdash":   0.35,
}
