"""Shared animation mappings and defaults for Player."""

STATE_ANIM_FALLBACK = {
    "idle": ["idle"],
    "walking": ["walk", "idle"],
    "running": ["run", "walk"],
    "jumping": ["run", "walk", "idle"],
    "falling": ["run", "walk", "idle"],
    "landing": ["idle", "walk"],
    "attacking": ["run", "walk"],
    "dodging": ["run", "walk"],
    "blocking": ["idle", "walk"],
    "casting": ["idle", "run"],
    "vaulting": ["run", "walk"],
    "climbing": ["run", "walk"],
    "wallrun": ["run", "walk"],
    "mounting": ["mounting", "climbing", "vaulting", "idle"],
    "mounted_idle": ["mounted_idle", "idle", "walk"],
    "mounted_move": ["mounted_move", "walk", "run"],
    "dismounting": ["dismounting", "landing", "idle"],
    "swim": ["swim", "walk", "idle"],
    "flying": ["flying", "jump", "run", "idle"],
    "fly": ["flying", "jump", "run", "idle"],
    "dead": ["idle"],
    "walk": ["walk", "idle"],
    "run": ["run", "walk"],
    "jump": ["run", "walk"],
}


ANIM_TOKEN_ALIASES = {
    "idleloop": ["idle"],
    "walkloop": ["walk"],
    "sprintloop": ["run", "walk"],
    "jumpstart": ["run", "walk"],
    "fallloop": ["run", "walk"],
    "jumpland": ["idle", "walk"],
    "swordslash": ["run", "walk"],
    "dodgebackward": ["run", "walk"],
    "blockidle": ["idle", "walk"],
    "spellcast": ["idle", "run"],
    "vaultover": ["run", "walk"],
    "ledgeclimb": ["run", "walk"],
    "wallrun": ["run", "walk"],
    "mountstart": ["mounting", "climbing", "vaulting", "idle"],
    "mounting": ["mounting", "climbing", "vaulting", "idle"],
    "mountedidle": ["mounted_idle", "idle", "walk"],
    "mountedmove": ["mounted_move", "walk", "run"],
    "dismount": ["dismounting", "landing", "idle"],
    "dismounting": ["dismounting", "landing", "idle"],
    "death": ["idle"],
    "swim": ["swim", "walk", "idle"],
    "flying": ["flying", "jump", "run", "idle"],
    "fly": ["flying", "jump", "run", "idle"],
    "hover": ["flying", "jump", "run", "idle"],
    "flight": ["flying", "jump", "run", "idle"],
    "jump": ["run", "walk"],
}


DEFAULT_STATE_DURATIONS = {
    "landing": 0.30,
    "attacking": 0.40,
    "dodging": 0.45,
    "casting": 0.55,
    "vaulting": 0.55,
    "climbing": 0.70,
    "wallrun": 0.60,
    "mounting": 0.55,
    "dismounting": 0.45,
    "dead": 1.20,
}
